// <auto-generated />
using System;
using GestaoPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestaoPI.Migrations
{
    [DbContext(typeof(GestaopiContext))]
    [Migration("20230329105859_InitMigration")]
    partial class InitMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_0900_ai_ci")
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");

            modelBuilder.Entity("GestaoPI.Models.Processo", b =>
                {
                    b.Property<string>("Codigo")
                        .HasMaxLength(19)
                        .HasColumnType("char(19)")
                        .HasColumnName("codigo")
                        .IsFixedLength();

                    b.Property<string>("Anotacao")
                        .HasColumnType("mediumtext")
                        .HasColumnName("anotacao");

                    b.Property<string>("CodigoNotificacao")
                        .HasMaxLength(11)
                        .HasColumnType("char(11)")
                        .HasColumnName("codigo_notificacao")
                        .IsFixedLength();

                    b.Property<DateOnly?>("Deposito")
                        .HasColumnType("date")
                        .HasColumnName("deposito");

                    b.Property<DateOnly?>("DominioPublico")
                        .HasColumnType("date")
                        .HasColumnName("dominio_publico");

                    b.Property<DateOnly?>("Exame")
                        .HasColumnType("date")
                        .HasColumnName("exame");

                    b.Property<string>("Resumo")
                        .HasColumnType("mediumtext")
                        .HasColumnName("resumo");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("enum('PI - Patente de Invenção','MU - Modelo de Utilidade','DI - Desenho Industrial')")
                        .HasColumnName("tipo");

                    b.Property<string>("Titulo")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("titulo");

                    b.HasKey("Codigo")
                        .HasName("PRIMARY");

                    b.ToTable("processo", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
